modLoader="javafml" 

loaderVersion="[34,)"

license="LGPL License"

issueTrackerURL="http://my.issue.tracker/" 

[[mods]] 

modId="swem" 

version="1.16.5-0.21.2.2-Alpha"

displayName="Star Worm Equestrian Mod" 

updateJSONURL="http://myurl.me/" 

displayURL="https://alaharranhonor.github.io" 

logoFile="icon.jpg" 

credits="legenden"

authors="AlaharranHonor"

description='''
Minecraft Java 1.16 (Forge) mod called Star Worm Equestrian Mod. The mod is bringing forward a whole new minecraft horse model, 18 horse coat textures, new animations, jumps, level progression, horse armor, tack, fencing, and stable decor ~ among other things.
'''

[[dependencies.swem]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.11]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.swem]] 
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.swem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
