name: Bug Report
description: Help fix an issue!
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Screenshots of what is happening can also be added here, via [link](https://gyazo.com/) or file. Please also list the steps to reproduce this error (if applicable).
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should happen?
      placeholder: Tell us what you were expecting to see!
      value: "I wanted horse to go zoom instead."
    validations:
      required: true
  - type: textarea
    id: mods
    attributes:
      label: Mods
      description: A list of mods and their version.
    validations:
      required: true

  - type: input
    id: swemVersion
    attributes:
      label: SWEM Version
      description:  What version of our mod are you using?
    validations:
      required: true
  - type: checkboxes
    id: worlds
    attributes:
      label: Singleplayer or Multiplayer
      description: Check the box on what world this issue has happened, you can check both if it appears on both a singleplayer and a server.
      options:
        - label: Singleplayer
        - label: Multiplayer
        - label: Other (Please add a comment to the issue where this is happening)
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you running?
      options:
        - Linux
        - Windows
        - Mac
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output (Crash Report if the game/server crashed, else paste the latest.log if it just happened, else a debug.log with a link to [pastebin](https://pastebin.com/)). This will be automatically formatted into code, so no need for backticks.
      render: shell
