name: 'Build'

on:
  #push:
  #  branches:
  #    - 'beta'
  pull_request:
    types:
      - opened
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v2
      - name: "Setup JDK 11"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "8" }
      - name: "Build with Gradle"
        id: build
        run: "chmod +x gradlew && ./gradlew build publish"